#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6451280351                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://stax-re.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Developer Direct NNN Investment Properties

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : STAX Real Estate                                
your_link                                 : https://stax-re.com                     
your_city                                 : Miami Beach                                
email_address                             : michael@staxvc.com
facebook_username                         :                                           
instagram_username                        : michaelcheckers
twitter_username                          : michaelsalafia
github_username                           : michaelsalafia
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Private Access to Exclusive Deals
    description                           : Our members receive exclusive access to a proprietary deal flow at above market returns. 
    fontawesome_icon_name                 : magic
    
  - title                                 : Developer Direct
    description                           : Our properties are coming directly from the developers, elimating the middlemen, and passing higher yeild returns to you.
    fontawesome_icon_name                 : mobile

  - title                                 : AI Powered Site Selection
    description                           : Our properitary AI powered workflow enables us to analyze hundreds of opportunties. The best options are hand selecte by experts from there. 
    fontawesome_icon_name                 : play-circle

  - title                                 : True Passive Income
    description                           : The Absolute NNN Leases on our properties have zero managment resposnbilties. Providing our investors with truely passive income streams. 
    fontawesome_icon_name                 : sync

  - title                                 : Tax Advantages
    description                           : Many of our properties are elible for accelerated depreciation and other tax savings programs.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Above Market Returns
    description                           : We are able to achieve significantly higher profit margins by sourcing all of our own deals, and cutting out the bloated banks and national brokerage firms. 
    fontawesome_icon_name                 : star

  - title                                 : Streamlined Process
    description                           : Our members enjoy the benefits of not only first access but our off-market streamlined investment process allows us to offer you better cap rates due to increased efficiency, reduced complexity, and faster decision-making. Investors can focus on evaluating opportunities and making informed choices.  
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : High Quaility Properties
    description                           : We conduct extensive due dilligence on every property, and only select the investment worthy assets. 
    fontawesome_icon_name                 : link

  - title                                 : Perfect for 1031X
    description                           : The long term corporate gauranteed NNN leases make great cadidates for 1031 exchange properties.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage-1.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
